# Generated by Django 5.2.8 on 2025-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betkarting_app', '0002_alter_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_fin_paris',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
