# Generated by Django 5.2.8 on 2025-11-20 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betkarting_app', '0003_course_date_fin_paris'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='resultat_calcule',
            field=models.BooleanField(default=False),
        ),
    ]
