# Generated by Django 5.2.8 on 2025-11-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betkarting_app', '0004_course_date_debut_course_resultat_calcule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gagnant_des_courses', to='betkarting_app.pilote'),
        ),
    ]
